### ISSUE TITLE
Final Cleanup of code

### ISSUE THREAD

**Issue by mjhajharia** [mjhajharia/transforms#16]
- [ ] Cleanup code properly - e.g. remove the draft scripts
- [ ] check if bounded transforms or other ones work properly in this mechanism
- [ ] get plots from n=100 repeated versions of the transforms

**Comment by bob-carpenter** [comment]
@mjahjaria---I find it easier to work with issues if each is about one thing.  It might also help to formulate them more explicitly---for example, in the second checkbox, what's "this mechanism" and what "bounded transforms" and for the second checkbox, which transforms?  100 repeated versions of what?

**Comment by mjhajharia** [comment]
closing with #18 #19 #20
