### ISSUE TITLE
Tasks for this week (27th June - 3rd July)

### ISSUE THREAD

**Issue by mjhajharia** [mjhajharia/transforms#2]
- [ ] Draft of Introduction
- [ ] Draft of Transforms section (Describing the theory of the transforms - i've been looking up original mentions of them for references)
- [x] Plotting the CDF and rmse/leapfrog after sampling them maybe a 1000 times and getting the average plots
- [ ] Bob suggested trying ess per leapfrog step as the x axis in the cdf plot
- [ ] understanding the geometry better:
            - [ ] behavior of tail
            - [ ] convexity
            - [ ] (needs more thought and discussion)

- [x] Starting with simpler transforms like exp or something for lower upper constraints

Note: Depending on how the actual process goes we might not be able to do all of this but I'd want us to do like 4 out of 6 maybe?

**Comment by sethaxen** [comment]
> * [ ]  Draft of Transforms section (Describing the theory of the transforms - i've been looking up original mentions of them for references)

I was planning on writing up the theory of transforms in general (at least for the simple case of Lebesgue measure). Is this what you had in mind here, or are you thinking more about the specific transforms we're currently comparing?

More generally, are these tasks we may individually claim, or are these all tasks you have claimed?

**Comment by mjhajharia** [comment]
Hi! So, let's individually claim tasks and we can review each other's progress in PRs, I did some code cleanup and stuff, mainly - I made some scripts for the sampling and storing, so I can sample for whatever plot we want on the cluster here and then save the result for a mean of 100 times. So eventually with the saved data, the plotting or analysis will be a separate thing and having a clean pipeline for this is useful for the next few weeks. I spent a little too much time fidgeting with this code, so I'll write up the individual simplex transforms and you can take up the general theory of transforms, and it would be nice if we made new branches and kept updating our progress there so the other people know what's going on. also i'm sorry for the late reply!

**Comment by sethaxen** [comment]
> you can take up the general theory of transforms, and it would be nice if we made new branches and kept updating our progress there so the other people know what's going on.

Great! I'll work on this later this week.

> also i'm sorry for the late reply!

No problem!

**Comment by mjhajharia** [comment]
created individual issues instead!
