### ISSUE TITLE
ESS/nsteps vs ESS/s

### ISSUE THREAD

**Issue by sethaxen** [mjhajharia/transforms#21]
In #8 we agreed on plotting KDE of ESS/nsteps, but I just remembered that this is still only a proxy for what we are really probably interested in, which is how much computational work is required to get the target ESS. e.g. take transforms `f` and `g`. If the gradient of `f` is 10x more expensive than that of `g`, but `f` has double the ESS/nsteps, Then we would prefer `f` if comparing ESS/nsteps but clearly prefer `g` if looking at ESS/s. ESS/s captures both, so perhaps that's a more relevant metric to report.

**Comment by bob-carpenter** [comment]
I agree that we should evaluate the efficiency of the actual transform, its log absolute determinant, and the gradient of the log absolute determinant, as they all get evaluated once as part of the log density and gradient calculation.  I don't know how to do that in a way that's not heavily implementation dependent.

I was hoping to just be able to use implementations in the Stan language to compare.  But those are very inefficient compared to the way we coded in C++ on the back end which includes analytic gradient code for the Jacobian determinants.

Instead, I'd like to report $\mathcal{O}(f(n))$ numbers for the transform/log abs det/gradient and the ESS/leapfrog steps in another.

Reviewers will almost certainly want wall time, so when we report that, we need to add the relevant red flags about implementation dependence.

**Comment by mjhajharia** [comment]
sorry this is dumb but what is s here? samples?
